test_that("conditionalCopy works", {
  withr::local_dir(withr::local_tempdir())
  expect_error(conditionalCopy(""), "No DESCRIPTION file found in")
  writeLines("Package: lucode2", "DESCRIPTION")
  dir.create("a")
  writeLines("1", "a/b.test")
  dir.create("inst/extdata", recursive = TRUE)
  conditionalCopy("a/b.test")
  expect_silent(conditionalCopy("a/b.test"))
  expect_identical(readLines("inst/extdata/b.test"), "1")
  writeLines("2", "a/b.test")
  expect_error(conditionalCopy("a/b.test"), "a/b.test != inst/extdata/b.test", fixed = TRUE)
  writeLines("Package: not-lucode2", "DESCRIPTION")
  conditionalCopy("inst/apfelkuchen.yaml", "lucode2-check.yaml")
  expect_gt(length(readLines("inst/apfelkuchen.yaml")), 0)
  writeLines("", "test_overwrite")
  conditionalCopy("test_overwrite", "lucode2-check.yaml")
  expect_gt(length(readLines("test_overwrite")), 1)
})
